# SPDX-FileCopyrightText: <text>Copyright 2023-2024 Arm Limited and/or its
# affiliates <open-source-office@arm.com></text>
#
# SPDX-License-Identifier: MIT
---
version: "2"
plugins:
  duplication:
  structure:
  pep8:
    enabled: true
  sonar-python:
    enabled: true
  shellcheck:
    enabled: true
    file_types:
      - "bash script"
      - "bats script"
      - "shell script"
    exclude_patterns:
      - "/public"
  fixme:
    enabled: true
    exclude_patterns:
      - "/Dangerfile"
      - "/public"
  cspell:
    enabled: true
    exclude_patterns:
      - GITIGNORE_CONTENTS
      - ".gitignore"
      - ".gitlab"
      - ".csslintrc"
      - ".eslintignore"
      - "coffeelint.json"
      - ".eslintrc.yml"
      - ".rubocop.yml"
      - "**.patch"
      - "**.svg"
      - "/public"
    dict_path: ".dictionary"
  yamllint:
    enabled: true
    exclude_patterns:
      - ".eslintrc.yml"
      - ".rubocop.yml"
      - "/public"
  headercheck:
    enabled: true
    format_rule: format-1
    original_works_licenses:
      - "Apache-2.0"
      - "GPL-2.0-only"
      - "MIT"
    external_works_licenses:
      - "Apache-2.0"
      - "BSD-3-Clause"
      - "MIT"
    exclude_patterns:
      - GITIGNORE_CONTENTS
      - "*.cfg"
      - "*.css"
      - "*.git"
      - "*.gitignore"
      - "*.log"
      - "*.patch"
      - "*.png"
      - "*.scc"
      - "*__init__.py"
      - ".csslintrc"
      - ".eslintignore"
      - ".eslintrc.yml"
      - ".rubocop.yml"
      - "/license.rst"
      - "coffeelint.json"
      - "/public"
  oelint-adv:
    enabled: true
    suppressions:
      # Not all suggested variables are applicable to all files.
      - 'oelint.var.suggestedvar'
      # 'BBCLASSEXTEND' variable will only be set when required.
      # Hence, we don't need to set it for all recipes.
      - 'oelint.var.bbclassextend'
      # Anonymous python functions are used to perform specific
      # processing during the parsing process.
      - 'oelint.task.noanonpython'
      # Some filenames have - in the version number.
      - 'oelint.file.underscores'
      # Codeclimate disables network access which prevents
      # oelint-adv from pinging the URLs.
      - 'oelint.vars.homepageping'
      # In some cases, we want to use the include directive.
      # But for some reason, the in-line suppression for this
      # check doesn't work.
      - 'oelint.file.requireinclude'
      # Usage of heredocs is very minimal
      # and does not deserve creating separate files.
      - 'oelint.task.heredocs'
      # The oelint-adv is not able to find .inc files from other layers
      # and the in-line suppression for this check doesn't work.
      - 'oelint.file.requirenotfound'
      # This check is done for all variables,
      # and suppressing it for each case is not feasible.
      - 'oelint.vars.multilineident'
      # This check does not support custom overrides
      - 'oelint.vars.specific'
      # This check does not support custom overrides
      - oelint.func.specific
      # In some cases, we want to use SRC_URI from different domains,
      # which makes this check fail. Disable it.
      - oelint.vars.srcuridomains
      # Having custom reasoning after Patches with
      # Upstream-Status: Inappropriate is desired
      - oelint.file.inappropriatemsg
    exclude_patterns:
      - "/public"
