# Copyright (c) 2023 Arm Limited or its affiliates. All rights reserved.
#
# SPDX-License-Identifier: MIT
---
version: "2"
plugins:
  duplication:
  structure:
    exclude_patterns:
      - "/documentation/variables.py"
  pep8:
    enabled: true
    exclude_patterns:
      - "/documentation/variables.py"
  sonar-python:
    enabled: true
  shellcheck:
    enabled: true
    file_types:
      - "bash script"
      - "bats script"
      - "shell script"
  fixme:
    enabled: true
    exclude_patterns:
      - "/Dangerfile"
  spellcheck:
    enabled: true
    exclude_patterns:
      - GITIGNORE_CONTENTS
      - "*.git"
      - "*.json"
      - "*.yaml"
      - "*.yml"
      - ".csslintrc"
      - ".eslintignore"
      - ".gitignore"
      - ".gitlab/"
      - "/documentation/*.py"
      - "/documentation/_static/"
      - "/documentation/license_link.rst"
      - "/documentation/requirements.txt"
      - "/layers/"
      - "Dangerfile"
      - "__pycache__"
      - "config/"
      - "license.rst"
      - "yocto/"
    dict_path: "config/qa-checks/dictionary.txt"
  yamllint:
    enabled: true
    exclude_patterns:
      - ".eslintrc.yml"
      - ".rubocop.yml"
  headercheck:
    enabled: true
    original_works_licenses:
      - "Apache-2.0"
      - "GPL-2.0-only"
      - "MIT"
    external_works_licenses:
      - "MIT"
    exclude_patterns:
      - GITIGNORE_CONTENTS
      - "*.cfg"
      - "*.css"
      - "*.git"
      - "*.gitignore"
      - "*.log"
      - "*.patch"
      - "*.png"
      - "*.scc"
      - "*.svg"
      - "*__init__.py"
      - ".csslintrc"
      - ".eslintignore"
      - ".eslintrc.yml"
      - ".gitlab"
      - ".rubocop.yml"
      - "/config/qa-checks/dictionary.txt"
      - "/license.rst"
      - "coffeelint.json"
