# SPDX-FileCopyrightText: <text>Copyright 2023 Arm Limited and/or its
# affiliates <open-source-office@arm.com></text>
#
# SPDX-License-Identifier: MIT
---
variables:
  CI_DEBUG_TRACE:
    value: 'false'
    description: Enable debug information output to the log
                 (true, false)
  FREQUENCY:
    value: adhoc
    description: How frequently is this build run
                 (adhoc, nightly, weekly)

# Include jobs
include:
  - project: $PIPELINE_TEMPLATE_PROJECT
    ref: v1.4.2
    file:
      - gitlab-ci/common_gitlab-ci.yml
      - gitlab-ci/danger-review_gitlab-ci.yml
      - gitlab-ci/static-analysis_gitlab-ci.yml
      - gitlab-ci/yocto-build-base_gitlab-ci.yml
      - gitlab-ci/kas-build-base_gitlab-ci.yml
  - local: '.gitlab/ci/rules.yml'
  - local: '.gitlab/ci/docs-build.yml'
  - local: '.gitlab/ci/kronos-build.yml'
  - local: '.gitlab/ci/yocto-qa.yml'
