# SPDX-FileCopyrightText: <text>Copyright 2023 Arm Limited and/or its
# affiliates <open-source-office@arm.com></text>
#
# SPDX-License-Identifier: MIT
---
variables:
  BUILD_HOST_ARCH:
    value: x86_64
    description: What build host architecture should be used
                 (x86_64, arm64)
  BUILD_IMAGE:
    value: none
    description: Comma separated list of images to build
                 (none)
  CI_DEBUG_TRACE:
    value: 'false'
    description: Enable debug information output to the log
                 (true, false)
  DOCKER_IMAGE_TAG:
    value: $CI_COMMIT_REF_SLUG
    description: Name tag used by the Docker image
  FORCE_TESTS:
    value: none
    description: Comma separated list of tests that must be run
                 (none)
  FREQUENCY:
    value: adhoc
    description: How frequently is this build run
                 (adhoc, nightly, weekly)
  RELEASE_BRANCH:
    value: main
    description: Target release branch

# Include jobs
include:
  - project: $PIPELINE_TEMPLATE_PROJECT
    ref: v1.1.2
    file:
      - gitlab-ci/common_gitlab-ci.yml
      - gitlab-ci/docker-image-base_gitlab-ci.yml
      - gitlab-ci/child-pipeline_gitlab-ci.yml
      - gitlab-ci/danger-review_gitlab-ci.yml
      - gitlab-ci/static-analysis_gitlab-ci.yml
  - local: '.gitlab/ci/rules.yml'
  - local: '.gitlab/ci/docker-image-builds.yml'
  - local: '.gitlab/ci/kronos-image-builds.yml'
  - local: '.gitlab/ci/trigger-image-builds.yml'
  - local: '.gitlab/ci/docs-build.yml'
