CONFIG_NET_CONFIG_SETTINGS=n

CONFIG_IPC_RPMSG_VETH_SI_IPV4_ADDR_0=""
CONFIG_IPC_RPMSG_VETH_SI_NETMASK_0=""

CONFIG_NET_IFACE1_ADDR="192.168.2.1"
CONFIG_NET_IFACE1_NETMASK="255.255.255.0"
CONFIG_NET_IFACE1_VLAN=300

CONFIG_NET_IFACE2_ADDR="192.168.10.2"
CONFIG_NET_IFACE2_GW="192.168.10.254"
CONFIG_NET_IFACE2_NETMASK="255.255.255.0"