#
# SPDX-FileCopyrightText: <text>Copyright 2024 Arm Limited and/or its
# affiliates <open-source-office@arm.com></text>
#
# SPDX-License-Identifier: MIT

# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "meta-arm-safety-island"
BBFILE_PATTERN_meta-arm-safety-island = "^${LAYERDIR}/"

LAYERDEPENDS_meta-arm-safety-island = "\
    core \
    zephyrcore \
"
LAYERSERIES_COMPAT_meta-arm-safety-island = "scarthgap"

ERROR_QA:append:layer-meta-arm-safety-island = " patch-status"

ARM_AUTO_SOLUTIONS_REPO_DIRECTORY = "${LAYERDIR}/../../"

addpylib ${LAYERDIR}/lib oeqa
