# SPDX-FileCopyrightText: <text>Copyright 2023 Arm Limited and/or its
# affiliates <open-source-office@arm.com></text>
#
# SPDX-License-Identifier: Apache-2.0

CONFIG_TFM_PSA_PROTECTED_STORAGE_API=y
CONFIG_TFM_PSA_INTERNAL_TRUSTED_STORAGE_API=y
CONFIG_PSA_ARCH_TEST_STORAGE=y
CONFIG_PSA_ARCH_TEST_API_TFM_HEADERS=y
