#
# SPDX-FileCopyrightText: <text>Copyright 2023 Arm Limited and/or its
# affiliates <open-source-office@arm.com></text>
#
# SPDX-License-Identifier: Apache-2.0

CONFIG_NET_CONFIG_SETTINGS=n

CONFIG_NET_IFACE1_ADDR="192.168.10.0"
CONFIG_NET_IFACE1_GW="192.168.10.254"
CONFIG_NET_IFACE1_NETMASK="255.255.255.0"

CONFIG_NET_IFACE2_ADDR="192.168.0.1"
CONFIG_NET_IFACE2_NETMASK="255.255.255.0"
CONFIG_NET_IFACE2_VLAN=100

CONFIG_NET_IF_MAX_IPV4_COUNT=2

CONFIG_MDIO=y
CONFIG_MDIO_SHELL=n
CONFIG_MDIO_INIT_PRIORITY=82
CONFIG_PHY_INIT_PRIORITY=83

CONFIG_DDS_NETWORK_INTERFACE="veth_rpmsg"

CONFIG_IPC_RPMSG_VETH=n
