#
# SPDX-FileCopyrightText: <text>Copyright 2023-2024 Arm Limited and/or its
# affiliates <open-source-office@arm.com></text>
#
# SPDX-License-Identifier: MIT

# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "meta-arm-auto-solutions"
BBFILE_PATTERN_meta-arm-auto-solutions = "^${LAYERDIR}/"

LAYERDEPENDS_meta-arm-auto-solutions = "\
    core \
    meta-arm-bsp \
    zephyrcore \
    parsec-layer \
    meta-cassini-distro \
"
LAYERSERIES_COMPAT_meta-arm-auto-solutions = "scarthgap"

# In this layer we are using Xen without the virtualization DISTRO_FEATURE
SKIP_META_VIRT_SANITY_CHECK = "1"

# Apply image features configurations
USER_CLASSES:append = " arm_auto_solutions_image_features"

ARM_AUTO_SOLUTIONS_REPO_DIRECTORY = "${LAYERDIR}/../../"

addpylib ${LAYERDIR}/lib oeqa
