#
# SPDX-FileCopyrightText: <text>Copyright 2023-2024 Arm Limited and/or its
# affiliates <open-source-office@arm.com></text>
#
# SPDX-License-Identifier: MIT

MACHINE = "${DOMU_MACHINE}"
MACHINE_FEATURES:remove = "rtc"

TUNE_CCARGS_MARCH_OPTS .= "+sve"

EXTRA_IMAGE_FEATURES:remove = "virtualization"
EXTRA_IMAGE_FEATURES:append = " domu"

# QEMU is only used to generate qcow2 images, so remove unneeded items from its
# PACKAGECONFIG
PACKAGECONFIG:remove:pn-qemu-system-native = "alsa virglrenderer epoxy"

# Xen guests uses console hvc0
SERIAL_CONSOLES = "115200;hvc0"

# Use a separate TMPDIR
TMPDIR = "${DOMU_TMPDIR}"

# Don't include kernel binary in rootfs /boot path
RRECOMMENDS:${KERNEL_PACKAGE_NAME}-base = ""

# DomU is booted/started by Dom0, hence we don't need an EFI loader for it
EFI_PROVIDER = ""
# Currently, poky comes with a default value for INITRAMFS_MAXSIZE of
# 131072(K). To add more packages, increase the INITRAMFS_MAXSIZE to 500000(K).
# Note: The INITRAMFS_MAXSIZE value should be less that 1/2 of the ram size.
INITRAMFS_MAXSIZE = "500000"
