# SPDX-FileCopyrightText: <text>Copyright 2023 Arm Limited and/or its
# affiliates <open-source-office@arm.com></text>
#
# SPDX-License-Identifier: Apache-2.0

CONFIG_COMPILER_WARNINGS_AS_ERRORS=y

CONFIG_FAULT_MGMT=y
CONFIG_FAULT_MGMT_SHELL=y

CONFIG_LOG=y
CONFIG_SHELL_MINIMAL=y
CONFIG_LOG_MODE_MINIMAL=y
