# SPDX-FileCopyrightText: <text>Copyright 2023 Arm Limited and/or its
# affiliates <open-source-office@arm.com></text>
#
# SPDX-License-Identifier: Apache-2.0

CONFIG_COMPILER_WARNINGS_AS_ERRORS=y
CONFIG_SHELL_STACK_SIZE=4096

CONFIG_FAULT_MGMT=y
CONFIG_FAULT_MGMT_SHELL=y
CONFIG_FAULT_MGMT_STACK_SIZE=2048

CONFIG_LOG=y

CONFIG_FAULT_MGMT_STORAGE_SYS_HASH_MAP=y
CONFIG_COMMON_LIBC_MALLOC_ARENA_SIZE=4096
