#
# SPDX-FileCopyrightText: <text>Copyright 2023 Arm Limited and/or its
# affiliates <open-source-office@arm.com></text>
#
# SPDX-License-Identifier: Apache-2.0

# Disable the IPC service
CONFIG_IPC_SERVICE=n
CONFIG_IPC_RPMSG_VETH=n

# Enable networking
CONFIG_CAM_SERVICE_IP="192.168.1.1"
CONFIG_NET_L2_ETHERNET=y
CONFIG_NET_CONFIG_SETTINGS=y
CONFIG_NET_MAX_CONTEXTS=10
CONFIG_NET_MAX_CONN=10

# Log config
CONFIG_CAM_LOG_LEVEL=3
CONFIG_FS_LOG_LEVEL_OFF=y

# FS config
CONFIG_FS_FATFS_REENTRANT=y
