#
# SPDX-FileCopyrightText: <text>Copyright 2023 Arm Limited and/or its
# affiliates <open-source-office@arm.com></text>
#
# SPDX-License-Identifier: Apache-2.0

# Disable the IPC service
CONFIG_IPC_SERVICE=n
CONFIG_IPC_RPMSG_VETH=n

# Enable networking
CONFIG_NET_L2_ETHERNET=y
CONFIG_NET_CONFIG_SETTINGS=y
