#
# SPDX-FileCopyrightText: <text>Copyright 2023 Arm Limited and/or its
# affiliates <open-source-office@arm.com></text>
#
# SPDX-License-Identifier: MIT

---
header:
  version: 13
  includes:
    - yocto/kas/include/cassini.yml
    - repo: meta-arm
      file: kas/fvp-rd-kronos.yml

defaults:
  repos:
    refspec: langdale

repos:
  kronos:
    layers:
      yocto/meta-kronos:

  meta-arm:
    layers:
      meta-arm: included
      meta-arm-toolchain: included
      meta-arm-bsp: included

  meta-zephyr:
    url: https://git.yoctoproject.org/git/meta-zephyr
    path: layers/meta-zephyr
    layers:
      meta-zephyr-core:

env:
  TESTIMAGE_AUTO:

local_conf_header:
  kronos-extra-features: |
    EXTRA_IMAGE_FEATURES:append = " hipc-validation"
  diskmon: |
    BB_DISKMON_DIRS = "\
      STOPTASKS,${TMPDIR},1G,100K \
      STOPTASKS,${DL_DIR},1G,100K \
      STOPTASKS,${SSTATE_DIR},1G,100K \
      STOPTASKS,/tmp,100M,100K \
      HALT,${TMPDIR},100M,1K \
      HALT,${DL_DIR},100M,1K \
      HALT,${SSTATE_DIR},100M,1K \
      HALT,/tmp,10M,1K"

distro: cassini
