// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file VehicleEmergencyStamped.c
 * This source file contains the definition of the described types in the IDL file.
 *
 * This file was generated by the tool gen.
 */

#include "VehicleEmergencyStamped.h"

#include <ucdr/microcdr.h>
#include <string.h>

bool builtin_interfaces_msg_Time_serialize_topic(ucdrBuffer* writer, const builtin_interfaces_msg_Time* topic)
{
    bool success = true;

        success &= ucdr_serialize_int32_t(writer, topic->sec);

        success &= ucdr_serialize_uint32_t(writer, topic->nanosec);

    return success && !writer->error;
}

bool builtin_interfaces_msg_Time_deserialize_topic(ucdrBuffer* reader, builtin_interfaces_msg_Time* topic)
{
    bool success = true;

        success &= ucdr_deserialize_int32_t(reader, &topic->sec);

        success &= ucdr_deserialize_uint32_t(reader, &topic->nanosec);

    return success && !reader->error;
}

uint32_t builtin_interfaces_msg_Time_size_of_topic(const builtin_interfaces_msg_Time* topic, uint32_t size)
{
    uint32_t previousSize = size;
        size += ucdr_alignment(size, 4) + 4;

        size += ucdr_alignment(size, 4) + 4;

    return size - previousSize;
}

bool tier4_vehicle_msgs_msg_VehicleEmergencyStamped_serialize_topic(ucdrBuffer* writer, const tier4_vehicle_msgs_msg_VehicleEmergencyStamped* topic)
{
    bool success = true;

        success &= builtin_interfaces_msg_Time_serialize_topic(writer, &topic->stamp);
        success &= ucdr_serialize_bool(writer, topic->emergency);

    return success && !writer->error;
}

bool tier4_vehicle_msgs_msg_VehicleEmergencyStamped_deserialize_topic(ucdrBuffer* reader, tier4_vehicle_msgs_msg_VehicleEmergencyStamped* topic)
{
    bool success = true;

        success &= builtin_interfaces_msg_Time_deserialize_topic(reader, &topic->stamp);
        success &= ucdr_deserialize_bool(reader, &topic->emergency);

    return success && !reader->error;
}

uint32_t tier4_vehicle_msgs_msg_VehicleEmergencyStamped_size_of_topic(const tier4_vehicle_msgs_msg_VehicleEmergencyStamped* topic, uint32_t size)
{
    uint32_t previousSize = size;
        size += builtin_interfaces_msg_Time_size_of_topic(&topic->stamp, size);
        size += ucdr_alignment(size, 1) + 1;

    return size - previousSize;
}
