# SPDX-FileCopyrightText: <text>Copyright 2023-2024 Arm Limited and/or its
# affiliates <open-source-office@arm.com></text>
#
# SPDX-License-Identifier: MIT

# Configuration file for the Sphinx documentation builder.
#
# This file only contains a selection of the most common options. For a full
# list see the documentation:
# [inclusivity-exception]
# https://www.sphinx-doc.org/en/master/usage/configuration.html

# -- Path setup --------------------------------------------------------------

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute.

import os
import sys

# -- Project information -----------------------------------------------------

project = 'Arm Automotive Solutions'
copyright = '2023-2024, Arm Limited (or its affiliates).'
author = 'Arm Ltd.'


# -- General configuration ---------------------------------------------------

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
    'sphinx.ext.autosectionlabel',
    'sphinx.ext.extlinks',
    'sphinx_rtd_theme',
    'sphinx_copybutton',
    'sphinx_substitution_extensions',
]

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = 'en'

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This pattern also affects html_static_path and html_extra_path.
exclude_patterns = ['_build', 'Thumbs.db', '.DS_Store']

# -- Options for HTML output -------------------------------------------------

# Define the canonical URL if you are using a custom domain on Read the Docs
html_baseurl = os.environ.get("READTHEDOCS_CANONICAL_URL", "")

# Tell Jinja2 templates the build is running on Read the Docs
html_context = {
    'READTHEDOCS': os.environ.get("READTHEDOCS", "") == "True"
}

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#
html_theme = 'sphinx_rtd_theme'

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ['_static']

html_css_files = [
    'css/custom.css',
]

# Don't show the "Built with Sphinx" footer
html_show_sphinx = False

html_theme_options = {
    'collapse_navigation': False,
    'navigation_depth': 5,
    'prev_next_buttons_location': "both",
    'style_external_links': True
}

# -- Extension configuration -------------------------------------------------

# -- Options for autosectionlabel --------------------------------------------

# Prefix each section label with the name of the document it is in
autosectionlabel_prefix_document = True
# Only generate automatic section labels for document titles
autosectionlabel_maxdepth = 1

# -- Options for copybutton --------------------------------------------------
copybutton_copy_empty_lines = False
copybutton_line_continuation_character = "\\"
copybutton_only_copy_prompt_lines = True
copybutton_prompt_is_regexp = True
copybutton_prompt_text = r'\$ '
copybutton_remove_prompts = True

# LaTeX settings for pdf generation
latex_toplevel_sectioning = None
latex_copyright = copyright
latex_elements = {
    'releasename': "Version",
    'preamble': r'''
\makeatletter
   \fancypagestyle{normal}{
% this is the footer section in sphinx.sty
    \fancyhf{}
    \fancyfoot[LE,RO]{{\py@HeaderFamily\thepage}}
% comment this out and
    %\fancyfoot[LO]{{\py@HeaderFamily\nouppercase{\rightmark}}}
    %\fancyfoot[RE]{{\py@HeaderFamily\nouppercase{\leftmark}}}
% add copyright content
    \fancyfoot[LO,RE]{{\textcopyright\ Copyright latex_copyright}}
% again original content
    \fancyhead[LE,RO]{{\py@HeaderFamily \@title\sphinxheadercomma\py@release}}
    \renewcommand{\headrulewidth}{0.4pt}
    \renewcommand{\footrulewidth}{0.4pt}
    }
% this is applied to each opening page of a chapter
   \fancypagestyle{plain}{
    \fancyhf{}
    \fancyfoot[LE,RO]{{\py@HeaderFamily\thepage}}
    \renewcommand{\headrulewidth}{0pt}
    \renewcommand{\footrulewidth}{0.4pt}
% add copyright content for example at left of footer on odd pages,
% which is the case for chapter opening page by default
    \fancyfoot[LO,RE]{{\textcopyright\ Copyright latex_copyright}}
    }
\makeatother
'''.replace("latex_copyright", latex_copyright),
}

# The variable yocto_version needs to come first because
# there are variables that refer to it later.
yocto_version = "scarthgap"

arm_auto_solutions_version = os.environ.get(
    'READTHEDOCS_GIT_IDENTIFIER',
    os.environ.get(
        'CI_COMMIT_REF_NAME', 'main'))

# The following variables are mostly used for pdf generation
version = arm_auto_solutions_version
release = arm_auto_solutions_version

# Common variables for rst_prolog
cassini_version = "v2.0.0"
critical_application_monitoring_version = "v1.1"
ewaol_version = "ewaol-2.0.0"
kas_version = "4.3.2"
linux_version = "6.6"
linux_version_patch = "35"
mbedtls_version = "1ec69067fa1351427f904362c1221b31538c8b57"
meta_arm_revision = "38bce82e42ea093333a53c4a10e51d1b26cbc989"
meta_cassini_revision = "bef1d728c6db464ff89828afae5b51e648058f35"
meta_clang_revision = "0acff283249842eb1f617b20c2ed4ebf9f8e3557"
meta_ewaol_revision = "c28142e72691202ba55a954f0faaed4375615b68"
meta_oe_revision = "78a14731cf0cf38a19ff8bd0e9255b319afaf3a7"
meta_ptx_revision = "547b079bf309ebe1576aa5ae0d58564feb245a42"
meta_secure_core_revision = "f3f928d097917b8a131044fe718440eb7f7e381b"
meta_security_revision = "11ea91192d43d7c2b0b95a93aa63ca7e73e38034"
meta_virtualization_revision = "37c06acf58f9020bccfc61954eeefe160642d5f3"
meta_zephyr_revision = "763c72fc3088fc09ccfde6edfcdad43811d16616"
optee_version = "3.22.0"
psa_arch_tests_version = "v23.06_API1.5_ADAC_EAC"
poky_revision = "ca27724b44031fe11b631ee50eb1e20f7a60009d"
scp_firmware_base_version = "main branch post v2.13.0"
scp_firmware_version = "cc4c9e017348d92054f74026ee1beb081403c168"
systemready_ir_acs_version = "2.1.0"
trusted_firmware_a_base_version = "lts-v2.8.6"
trusted_firmware_a_version = "ff0bd5f9bb2ba2f31fb9cec96df917747af9e92d"
trusted_firmware_a_doc_version = "v2.8"
trusted_firmware_m_base_version = "main branch post v1.8.1"
trusted_firmware_m_version = "53aa78efef274b9e46e63b429078ae1863609728"
trusted_firmware_m_doc_version = "tf-mv2.1.0"
trusted_services_base_version = "main branch, post v1.0.0"
trusted_services_doc_version = "integration"
trusted_services_version = "602be607198ea784bc5ab1c0c9d3ac4e2c67f1d9"
uboot_version = "2023.07.02"
xen_version = "4.18"
zephyr_version = "3.5.0"
psa_crypto_api_version = "1.1"
psa_storage_api_version = "1.0"

rst_prolog = f"""
.. |Arm SystemReadyTM| replace:: Arm SystemReady\\ :sup:`TM`
.. |Arm| replace:: Arm\\ :sup:`®`
.. |Cortex| replace:: Arm\\ :sup:`®` Cortex\\ :sup:`®`
.. |Linux version| replace:: {linux_version}.{linux_version_patch}
.. |Neoverse| replace:: Arm\\ :sup:`®` Neoverse\\ :sup:`TM`
.. |OP-TEE version| replace:: {optee_version}
.. |SCP-firmware base version| replace:: {scp_firmware_base_version}
.. |SCP-firmware version| replace:: {scp_firmware_version}
.. |SystemReady IR ACS version| replace:: {systemready_ir_acs_version}
.. |Trusted Firmware-A base version| replace:: {trusted_firmware_a_base_version}
.. |Trusted Firmware-A version| replace:: {trusted_firmware_a_version}
.. |Trusted Firmware-M base version| replace:: {trusted_firmware_m_base_version}
.. |Trusted Firmware-M version| replace:: {trusted_firmware_m_version}
.. |Trusted Services base version| replace:: {trusted_services_base_version}
.. |Trusted Services version| replace:: {trusted_services_version}
.. |U-Boot version| replace:: {uboot_version}
.. |Xen version| replace:: {xen_version}
.. |Zephyr version| replace:: {zephyr_version}
.. |kas version| replace:: {kas_version}
.. |arm auto solutions remote| replace:: https://git.gitlab.arm.com/automotive-and-industrial/arm-auto-solutions/sw-ref-stack.git
.. |arm auto solutions repository| replace:: https://gitlab.arm.com/automotive-and-industrial/arm-auto-solutions/sw-ref-stack
.. |arm auto solutions version| replace:: {arm_auto_solutions_version}
.. |layer dependency statement| replace:: {arm_auto_solutions_version} branch
.. |meta-arm branch| replace:: {yocto_version}
.. |meta-arm repository| replace:: https://git.yoctoproject.org/meta-arm
.. |meta-arm revision| replace:: {meta_arm_revision}
.. |meta-cassini branch| replace:: {yocto_version}
.. |meta-cassini repository| replace:: https://gitlab.com/Linaro/cassini/meta-cassini
.. |meta-cassini revision| replace:: {meta_cassini_revision}
.. |meta-clang branch| replace:: {yocto_version}
.. |meta-clang repository| replace:: https://github.com/kraj/meta-clang
.. |meta-clang revision| replace:: {meta_clang_revision}
.. |meta-ewaol branch| replace:: {yocto_version}
.. |meta-ewaol repository| replace:: https://gitlab.com/soafee/ewaol/meta-ewaol
.. |meta-ewaol revision| replace:: {meta_ewaol_revision}
.. |meta-openembedded branch| replace:: {yocto_version}
.. |meta-openembedded repository| replace:: https://git.openembedded.org/meta-openembedded
.. |meta-openembedded revision| replace:: {meta_oe_revision}
.. |meta-ptx branch| replace:: {yocto_version}
.. |meta-ptx repository| replace:: https://github.com/pengutronix/meta-ptx
.. |meta-ptx revision| replace:: {meta_ptx_revision}
.. |meta-secure-core branch| replace:: {yocto_version}
.. |meta-secure-core repository| replace:: https://github.com/Wind-River/meta-secure-core
.. |meta-secure-core revision| replace:: {meta_secure_core_revision}
.. |meta-security branch| replace:: {yocto_version}
.. |meta-security repository| replace:: https://git.yoctoproject.org/git/meta-security
.. |meta-security revision| replace:: {meta_security_revision}
.. |meta-virtualization branch| replace:: {yocto_version}
.. |meta-virtualization repository| replace:: https://git.yoctoproject.org/git/meta-virtualization
.. |meta-virtualization revision| replace:: {meta_virtualization_revision}
.. |meta-zephyr branch| replace:: {yocto_version}
.. |meta-zephyr repository| replace:: https://git.yoctoproject.org/git/meta-zephyr
.. |meta-zephyr revision| replace:: {meta_zephyr_revision}
.. |poky branch| replace:: {yocto_version}
.. |poky repository| replace:: https://git.yoctoproject.org/git/poky
.. |poky revision| replace:: {poky_revision}
.. |yocto version| replace:: {yocto_version}

.. _Arm Ecosystem FVPs: https://developer.arm.com/downloads/-/arm-ecosystem-fvps
.. _Arm Firmware Framework for Arm A-profile: https://developer.arm.com/documentation/den0077/latest
.. _Arm Memory Partitioning and Monitoring: https://developer.arm.com/documentation/ddi0598/latest
.. _Arm Reference Design-1 AE page on developer.arm.com: https://developer.arm.com/Tools%20and%20Software/Arm%20Reference%20Design-1%20AE
.. _Arm SystemReady IR: https://www.arm.com/architecture/system-architectures/systemready-certification-program/ir
.. _Arm SystemReady program: https://www.arm.com/architecture/system-architectures/systemready-certification-program
.. _Arm SystemReady: https://www.arm.com/architecture/system-architectures/systemready-certification-program
.. _Arm Trademark Policies: https://www.arm.com/company/policies/trademarks
.. _Autoware: https://autowarefoundation.github.io/autoware-documentation
.. _Base Boot Requirements (BBR): https://developer.arm.com/documentation/den0044/latest
.. _Base Boot Security Requirements (BBSR): https://developer.arm.com/documentation/den0107/latest
.. _Base System Architecture (BSA): https://developer.arm.com/documentation/den0094/latest
.. _Cassini Run-Time Integration Tests documentation: https://cassini.readthedocs.io/en/{cassini_version}/developer_manual/validation.html#run-time-integration-tests
.. _Critical Application Monitoring Documentation: https://critical-app-monitoring.docs.arm.com/en/{critical_application_monitoring_version}/
.. _Crypto Service: https://trusted-services.readthedocs.io/en/{trusted_services_doc_version}/services/crypto-service-description.html
.. _CycloneDDS: https://cyclonedds.io/docs/cyclonedds/latest/about_dds/eclipse_cyclone_dds.html
.. _Data Distribution Service: https://www.dds-foundation.org/what-is-dds-3
.. _Debian GNU/Linux Installation Guide: https://www.debian.org/releases/bookworm/arm64/
.. _Debian Stable: https://www.debian.org/releases/stable/
.. _Fedora Server: https://fedoraproject.org/server/download/
.. _Fedora Installation Guide: https://docs.fedoraproject.org/en-US/fedora/latest/getting-started/
.. _Device Tree specification: https://www.devicetree.org/
.. _EBBR Specification - Required Platform Specific Elements: https://arm-software.github.io/ebbr/index.html#required-platform-specific-elements
.. _EBBR Specification - UEFI Runtime Services: https://arm-software.github.io/ebbr/index.html#uefi-runtime-services
.. _EULA: https://developer.arm.com/downloads/-/arm-ecosystem-fvps/eula
.. _Embedded Base Boot Requirements (EBBR): https://developer.arm.com/architectures/platform-design/embedded-systems
.. _Ethernet Bridging API: https://docs.zephyrproject.org/apidoc/{zephyr_version}/group__eth__bridge.html
.. _EWAOL: https://gitlab.com/soafee/ewaol/meta-ewaol/-/tree/{ewaol_version}/
.. _Fast Models FVP Reference Guide: https://developer.arm.com/documentation/100966/latest
.. _GICv4.1 - Direct injection of virtual interrupts: https://developer.arm.com/documentation/107627/0101/GICv4-1---Direct-injection-of-virtual-interrupts
.. _GitLab Issues: https://gitlab.arm.com/automotive-and-industrial/arm-automotive-solutions/sw-ref-stack/-/issues
.. _IEEE 802.1AS: https://ieeexplore.ieee.org/document/9121845
.. _IEEE 802.1Q: https://ieeexplore.ieee.org/document/10004498
.. _IPC service: https://docs.zephyrproject.org/{zephyr_version}/services/ipc/ipc_service/ipc_service.html
.. _Kernel Types: https://docs.yoctoproject.org/{yocto_version}/kernel-dev/advanced.html#kernel-types
.. _Linux Boot for Security Interface Extension: https://developer.arm.com/documentation/102872/0101/Test-Security-Interface-Extension-compliance/Run-FWTS
.. _Linux PTP Project: https://linuxptp.sourceforge.net
.. _Linux preempt-rt repository: https://git.yoctoproject.org/linux-yocto/log/?h=v{linux_version}%2Fstandard%2Fpreempt-rt%2Fbase
.. _Linux repository: https://git.yoctoproject.org/linux-yocto/log/?h=v{linux_version}%2Fstandard%2Fbase
.. _MCUboot: https://docs.mcuboot.com/
.. _Mbed TLS repository: https://github.com/Mbed-TLS/mbedtls/tree/{mbedtls_version}
.. _Mbed TLS: https://mbed-tls.readthedocs.io/en/latest/
.. _OEQA FVP: https://git.yoctoproject.org/meta-arm/tree/documentation/oeqa-fvp.md?h={yocto_version}
.. _OP-TEE repository: https://github.com/OP-TEE/optee_os/tree/{optee_version}
.. _OP-TEE: https://optee.readthedocs.io/en/{optee_version}/
.. _OP-TEE API Specification: https://globalplatform.org/specs-library/?filter-committee=tee
.. _Open vSwitch: https://www.openvswitch.org
.. _PREEMPT_RT patch: https://wiki.linuxfoundation.org/realtime/start
.. _PSA Arch Tests: https://github.com/ARM-software/psa-arch-tests
.. _PSA Crypto API: https://arm-software.github.io/psa-api/crypto/{psa_crypto_api_version}
.. _PSA Crypto APIs Architecture Test Suite: https://github.com/ARM-software/psa-arch-tests/blob/{psa_arch_tests_version}/api-tests/docs/psa_crypto_testlist.md
.. _PSA Secure Storage API: https://arm-software.github.io/psa-api/storage/{psa_storage_api_version}
.. _PSA Secure Storage APIs Architecture Test Suite: https://github.com/ARM-software/psa-arch-tests/blob/{psa_arch_tests_version}/api-tests/docs/psa_storage_testlist.md
.. _Parsec Secure Element Driver: https://github.com/parallaxsecond/parsec-se-driver
.. _Parsec: https://parallaxsecond.github.io/parsec-book/index.html
.. _Platform Security Firmware Update Specification: https://developer.arm.com/documentation/den0118/latest
.. _Power Control System Architecture (PCSA): https://developer.arm.com/documentation/den0050/latest
.. _Pure Pursuit: https://autowarefoundation.gitlab.io/autoware.auto/AutowareAuto/pure-pursuit.html
.. _RSE provisioning: https://trustedfirmware-m.readthedocs.io/en/{trusted_firmware_m_doc_version}/platform/arm/rse/rse_provisioning.html
.. _Runtime Security Engine (RSE): https://trustedfirmware-m.readthedocs.io/en/{trusted_firmware_m_doc_version}/platform/arm/rse/readme.html
.. _SCP-firmware repository: https://github.com/ARM-software/SCP-firmware/tree/{scp_firmware_version}
.. _SCT for Security Interface Extension: https://developer.arm.com/documentation/102872/0101/Test-Security-Interface-Extension-compliance/Run-SCT
.. _SE Proxy SP: https://trusted-services.readthedocs.io/en/latest/deployments/secure-partitions.html#se-proxy
.. _SMM Gateway SP: https://trusted-services.readthedocs.io/en/{trusted_services_doc_version}/deployments/secure-partitions.html#smm-gateway
.. _SMM Variable Service: https://trusted-services.readthedocs.io/en/integration/services/uefi-smm-services.html#smm-variable-service
.. _Safety Island Actuation Demo: https://safety-island-actuation-demo.docs.arm.com
.. _Secure Partition: https://trusted-services.readthedocs.io/en/{trusted_services_doc_version}/environments/secure-partitions/index.html
.. _Secure Storage Service: https://trusted-services.readthedocs.io/en/{trusted_services_doc_version}/services/secure-storage-service-description.html
.. _Security Interface Extension (SIE): https://developer.arm.com/documentation/102872/0100
.. _SVE2 guide: https://developer.arm.com/documentation/102340/0100/Introducing-SVE2
.. _System Control Processor (SCP) Firmware: https://developer.arm.com/documentation/den0050/latest
.. _TF-M Crypto Service: https://trustedfirmware-m.readthedocs.io/en/{trusted_firmware_m_doc_version}/design_docs/services/tfm_crypto_design.html
.. _TF-M Internal Trusted Storage Service: https://trustedfirmware-m.readthedocs.io/en/{trusted_firmware_m_doc_version}/design_docs/services/tfm_its_service.html
.. _TF-M Secure Services: https://trustedfirmware-m.readthedocs.io/en/{trusted_firmware_m_doc_version}/design_docs/services/index.html
.. _TF-M Secure boot: https://trustedfirmware-m.readthedocs.io/en/{trusted_firmware_m_doc_version}/design_docs/booting/tfm_secure_boot.html
.. _Tmux Documentation: https://man7.org/linux/man-pages/man1/tmux.1.html
.. _Trusted Board Boot (TBB): https://trustedfirmware-a.readthedocs.io/en/{trusted_firmware_a_doc_version}/design/trusted-board-boot.html
.. _Trusted Board Boot Requirements (TBBR): https://developer.arm.com/documentation/den0006/latest
.. _TrustZone: https://www.arm.com/technologies/trustzone-for-cortex-a/tee-reference-documentation
.. _Trusted Firmware-A (TF-A): https://trustedfirmware-a.readthedocs.io
.. _Trusted Firmware-A repository: https://git.trustedfirmware.org/TF-A/trusted-firmware-a.git/+/{trusted_firmware_a_base_version}
.. _Trusted Firmware-M (TF-M): https://trustedfirmware-m.readthedocs.io/en/{trusted_firmware_m_doc_version}
.. _Trusted Firmware-M PSA Protected Storage Interfaces: https://trustedfirmware-m.readthedocs.io/en/{trusted_firmware_m_doc_version}/integration_guide/services/tfm_ps_integration_guide.html#psa-protected-storage-interfaces
.. _Trusted Firmware-M PSA Internal Trusted Storage Interfaces: https://trustedfirmware-m.readthedocs.io/en/{trusted_firmware_m_doc_version}/integration_guide/services/tfm_its_integration_guide.html#psa-internal-trusted-storage-interfaces
.. _Trusted Firmware-M repository: https://git.trustedfirmware.org/TF-M/trusted-firmware-m.git/+/{trusted_firmware_m_version}
.. _Trusted Services Test Executables: https://trusted-services.readthedocs.io/en/{trusted_services_doc_version}/deployments/test-executables.html
.. _Trusted Services repository: https://git.trustedfirmware.org/TS/trusted-services/+/{trusted_services_version}
.. _Trusted Services: https://trusted-services.readthedocs.io/en/{trusted_services_doc_version}/index.html
.. _U-Boot repository: https://source.denx.de/u-boot/u-boot/-/tree/v{uboot_version}
.. _U-boot: https://u-boot.readthedocs.io
.. _UEFI SMM Services: https://trusted-services.readthedocs.io/en/{trusted_services_doc_version}/services/uefi-smm-services.html
.. _UEFI Specification: https://uefi.org/specs/UEFI/2.10/index.html
.. _Writing New Tests: https://docs.yoctoproject.org/{yocto_version}/dev-manual/runtime-testing.html#writing-new-tests
.. _X.509 v3: https://www.rfc-editor.org/rfc/rfc5280.txt
.. _Xen Hypervisor: https://xenproject.org/help/documentation
.. _Xen repository: https://xenbits.xen.org/gitweb/?p=xen.git;a=tree;h=refs/heads/stable-{xen_version}
.. _Yocto Project Quick Start: https://docs.yoctoproject.org/{yocto_version}/brief-yoctoprojectqs/index.html
.. _Yocto Project: https://docs.yoctoproject.org/{yocto_version}/index.html
.. _Zephyr file system: https://docs.zephyrproject.org/{zephyr_version}/services/file_system/index.html
.. _Zephyr gPTP subsystem: https://docs.zephyrproject.org/{zephyr_version}/connectivity/networking/api/gptp.html
.. _Zephyr repository: https://github.com/zephyrproject-rtos/zephyr/tree/v{zephyr_version}
.. _Zephyr: https://docs.zephyrproject.org/{zephyr_version}/
.. _edk2-test-parser: https://gitlab.arm.com/systemready/edk2-test-parser/-/blob/ir1/EBBR.yaml
.. _how to install the essential packages: https://docs.yoctoproject.org/{yocto_version}/singleindex.html#ubuntu-and-debian
.. _imgtool: https://github.com/mcu-tools/mcuboot/blob/main/docs/imgtool.md
.. _kas Dependencies & installation: https://kas.readthedocs.io/en/{kas_version}/userguide.html#dependencies-installation
.. _kas build tool: https://kas.readthedocs.io/en/{kas_version}/userguide.html
.. _kas menu tool: https://kas.readthedocs.io/en/{kas_version}/userguide.html#module-kas.plugins.menu
.. _libts: https://trusted-services.readthedocs.io/en/{trusted_services_doc_version}/deployments/libraries.html#libts
.. _openSUSE Installation Guide: https://doc.opensuse.org/documentation/leap/startup/html/book-startup/part-basics.html
.. _openSUSE Leap: https://download.opensuse.org/distribution/leap/
.. _testimage.bbclass: https://docs.yoctoproject.org/{yocto_version}/ref-manual/classes.html#testimage
.. _xen-command-line options: https://xenbits.xen.org/docs/{xen_version}-testing/misc/xen-command-line.html#dom0
.. _xl configuration: https://xenbits.xen.org/docs/{xen_version}-testing/man/xl.cfg.5.html#Architecture-Specific-options
.. _xl documentation: https://xenbits.xen.org/docs/{xen_version}-testing/man/xl.1.html
.. _zperf sample: https://docs.zephyrproject.org/{zephyr_version}/connectivity/networking/api/zperf.html
"""  # noqa: E501

# URL to use for references to repository paths
repo_url_pattern = os.environ.get(
    'REPO_URL_PATTERN',
    'https://gitlab.arm.com/automotive-and-industrial/arm-auto-solutions/sw-ref-stack/-/tree/{ref}/{path}')  # noqa
# Read the Docs sometimes adds extra quotes to environment variables
repo_url_pattern = repo_url_pattern.strip("'")

meta_arm_url_repo_pattern = 'https://git.yoctoproject.org/meta-arm/tree/{path}?h={ref}'  # noqa

extlinks = {
            'meta-arm-repo': (meta_arm_url_repo_pattern.format(path='%s', ref=yocto_version), '%s'),  # noqa
            'repo': (repo_url_pattern.format(path='%s', ref=arm_auto_solutions_version), '%s'),  # noqa
            }
