# SPDX-FileCopyrightText: <text>Copyright 2023 Arm Limited and/or its
# affiliates <open-source-office@arm.com></text>
#
# SPDX-License-Identifier: MIT

# Configuration file for the Sphinx documentation builder.
#
# This file only contains a selection of the most common options. For a full
# list see the documentation:
# [inclusivity-exception]
# https://www.sphinx-doc.org/en/master/usage/configuration.html

# -- Path setup --------------------------------------------------------------

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute.

import os
import sys

# -- Project information -----------------------------------------------------

project = 'Arm Kronos Reference Stack'
copyright = '2023, Arm Ltd.'
author = 'Arm Ltd.'


# -- General configuration ---------------------------------------------------

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
    'sphinx.ext.autosectionlabel',
    'sphinx.ext.extlinks',
    'sphinx_rtd_theme',
    'sphinx_copybutton',
    'sphinx_substitution_extensions',
]

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = 'en'

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This pattern also affects html_static_path and html_extra_path.
exclude_patterns = ['_build', 'Thumbs.db', '.DS_Store']

# -- Options for HTML output -------------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#
html_theme = 'sphinx_rtd_theme'

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ['_static']

html_css_files = [
    'css/custom.css',
]

# Don't show the "Built with Sphinx" footer
html_show_sphinx = False

html_theme_options = {
    'collapse_navigation': False,
    'navigation_depth': 5,
    'prev_next_buttons_location': "both",
    'style_external_links': True
}

# -- Extension configuration -------------------------------------------------

# -- Options for autosectionlabel --------------------------------------------

# Prefix each section label with the name of the document it is in
autosectionlabel_prefix_document = True
# Only generate automatic section labels for document titles
autosectionlabel_maxdepth = 1

# -- Options for copybutton --------------------------------------------------
copybutton_prompt_text = r'\$ '
copybutton_prompt_is_regexp = True
copybutton_remove_prompts = True
copybutton_only_copy_prompt_lines = True
copybutton_copy_empty_lines = False
copybutton_line_continuation_character = "\\"

# Common variables for rst_prolog
yocto_version = "langdale"
yocto_doc_version = yocto_version + "/"
kronos_version = "main"
kas_version = "3.2"
trusted_firmware_m_version = "bd8c7c9c40e522d4db10d4b45412f7a56eb5dae7"
# [inclusivity-exception]
trusted_firmware_m_base_version = "master branch post v1.7.0"
scp_firmware_version = "f71f34237365b2c4b54be798aba79b740dcc4020"
# [inclusivity-exception]
scp_firmware_base_version = "master branch post v2.11.0"
trusted_firmware_a_version = "2.8.0"
uboot_version = "2022.07"
linux_version = "5.19"
linux_version_patch = "17"
xen_version = "4.16"

rst_prolog = f"""
.. |kas version| replace:: 3.2
.. |Arm| replace:: Arm\\ :sup:`®`
.. |Trusted Firmware-M version| replace:: {trusted_firmware_m_version}
.. |Trusted Firmware-M base version| replace:: {trusted_firmware_m_base_version}
.. |SCP-Firmware version| replace:: {scp_firmware_version}
.. |SCP-Firmware base version| replace:: {scp_firmware_base_version}
.. |Trusted Firmware-A version| replace:: {trusted_firmware_a_version}
.. |U-Boot version| replace:: {uboot_version}
.. |Xen version| replace:: {xen_version}
.. |Linux version| replace:: {linux_version}.{linux_version_patch}
.. |Arm SystemReadyTM| replace:: Arm SystemReady\\ :sup:`TM`
.. |kronos remote| replace:: https://git.gitlab.arm.com/automotive-and-industrial/kronos/kronos.git
.. |kronos version| replace:: {kronos_version}

.. _kas build tool: https://kas.readthedocs.io/en/{kas_version}/userguide.html
.. _how to install the essential packages: https://docs.yoctoproject.org/{yocto_doc_version}singleindex.html#required-packages-for-the-build-host
.. _kas Dependencies & installation: https://kas.readthedocs.io/en/{kas_version}/userguide.html#dependencies-installation
.. _EULA: https://developer.arm.com/downloads/-/arm-ecosystem-fvps/eula
.. _Writing New Tests: https://docs.yoctoproject.org/{yocto_doc_version}dev-manual/common-tasks.html#writing-new-tests
.. _testimage.bbclass: https://docs.yoctoproject.org/{yocto_doc_version}ref-manual/classes.html#testimage-bbclass
.. _OEQA FVP: https://git.yoctoproject.org/meta-arm/tree/documentation/oeqa-fvp.md?h={yocto_version}
.. _Trusted Firmware-M repository: https://git.trustedfirmware.org/TF-M/trusted-firmware-m.git/tree/?h={trusted_firmware_m_version}
.. _SCP-Firmware repository: https://github.com/ARM-software/SCP-firmware/tree/{scp_firmware_version}
.. _Trusted Firmware-A repository: https://git.trustedfirmware.org/TF-A/trusted-firmware-a.git/tree/?h=v{trusted_firmware_a_version}
.. _U-Boot repository: https://source.denx.de/u-boot/u-boot/-/tree/v{uboot_version}
.. _Xen repository: https://xenbits.xen.org/gitweb/?p=xen.git;a=tree;h=refs/heads/stable-{xen_version}
.. _Linux repository: https://git.yoctoproject.org/linux-yocto/log/?h=v{linux_version}%2Fstandard%2Fbase
.. _Device Tree specification: https://www.devicetree.org/
.. _xl documentation: https://xenbits.xen.org/docs/{xen_version}-testing/man/xl.1.html
.. _Arm Memory Partitioning and Monitoring: https://developer.arm.com/documentation/ddi0598/latest
"""  # noqa: E501

# URL to use for references to repository paths
repo_url_pattern = os.environ.get(
    'REPO_URL_PATTERN',
    'https://gitlab.arm.com/automotive-and-industrial/kronos/-/tree/{ref}/{path}')  # noqa
# Read the Docs sometimes adds extra quotes to environment variables
repo_url_pattern = repo_url_pattern.strip("'")

meta_arm_url_repo_pattern = os.environ.get(
    'META_ARM_REPO_URL_PATTERN',
    'https://git.yoctoproject.org/meta-arm/tree/{path}?h={ref}')
# Read the Docs sometimes adds extra quotes to environment variables
meta_arm_url_repo_pattern = meta_arm_url_repo_pattern.strip("'")
meta_arm_ref = os.environ.get('META_ARM_REF', yocto_version)

extlinks = {
            'meta-arm-repo': (meta_arm_url_repo_pattern.format(path='%s', ref=meta_arm_ref), '%s'),  # noqa
            'kronos-repo': (repo_url_pattern.format(path='%s', ref=kronos_version), '%s'),  # noqa
            }
